package ec.edu.scli.reservas.infrastructure.persistence.entity;
import jakarta.persistence.*; import java.time.*; import java.util.UUID;
import ec.edu.scli.reservas.domain.model.EstadoPlanificacion;
@Entity @Table(name="planificaciones_semestre") public class PlanificacionJpaEntity {
 @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; private UUID periodoId,carreraId,materiaId,docenteId,laboratorioId,creadoPorPerfilId,planificacionId; private Integer nivel;
 @Column(nullable=false) private String diaSemana; private LocalTime horaInicio,horaFin; @Enumerated(EnumType.STRING) private EstadoPlanificacion estado=EstadoPlanificacion.BORRADOR; private String observacion; private Instant creadaEn,actualizadaEn; @Version private Long version;
 public UUID getId(){return id;} public void setId(UUID v){id=v;} public UUID getPeriodoId(){return periodoId;} public void setPeriodoId(UUID v){periodoId=v;} public UUID getCarreraId(){return carreraId;} public void setCarreraId(UUID v){carreraId=v;} public UUID getMateriaId(){return materiaId;} public void setMateriaId(UUID v){materiaId=v;} public UUID getDocenteId(){return docenteId;} public void setDocenteId(UUID v){docenteId=v;} public UUID getLaboratorioId(){return laboratorioId;} public void setLaboratorioId(UUID v){laboratorioId=v;} public UUID getCreadoPorPerfilId(){return creadoPorPerfilId;} public void setCreadoPorPerfilId(UUID v){creadoPorPerfilId=v;} public String getDiaSemana(){return diaSemana;} public void setDiaSemana(String v){diaSemana=v;} public LocalTime getHoraInicio(){return horaInicio;} public void setHoraInicio(LocalTime v){horaInicio=v;} public LocalTime getHoraFin(){return horaFin;} public void setHoraFin(LocalTime v){horaFin=v;} public EstadoPlanificacion getEstado(){return estado;} public void setEstado(EstadoPlanificacion v){estado=v;} public String getObservacion(){return observacion;} public void setObservacion(String v){observacion=v;} public Instant getCreadaEn(){return creadaEn;} public void setCreadaEn(Instant v){creadaEn=v;} public Instant getActualizadaEn(){return actualizadaEn;} public void setActualizadaEn(Instant v){actualizadaEn=v;} public Long getVersion(){return version;} public void setVersion(Long v){version=v;}
 public UUID getPlanificacionId(){return planificacionId;} public void setPlanificacionId(UUID v){planificacionId=v;} public Integer getNivel(){return nivel;} public void setNivel(Integer v){nivel=v;}
}
