import { useEffect, useRef, useState, type FormEvent } from 'react'
import { DashboardLayout } from '../../components/DashboardLayout'
import { useAuth } from '../../auth'
import { obtenerLaboratorios, type Laboratorio } from '../../services/academicoApi'
import { consultarDisponibilidad, crearSolicitud, type CrearSolicitudReserva, type Disponibilidad } from './reservasApi'
import './Reservas.css'

const vacio = { docenteId: '', laboratorioId: '', materiaId: '', periodoLectivoId: '', fechaReserva: '', horaInicio: '', horaFin: '', numeroParticipantes: 1, motivo: '', observacion: '' }
export function NuevaSolicitudPage() {
  const { usuario } = useAuth(); const [form, setForm] = useState(vacio); const [laboratorios, setLaboratorios] = useState<Laboratorio[]>([]); const [enviando, setEnviando] = useState(false); const [error, setError] = useState<string | null>(null); const [exito, setExito] = useState<string | null>(null); const [disponibilidad, setDisponibilidad] = useState<Disponibilidad | null>(null); const [consultando, setConsultando] = useState(false); const key = useRef(crypto.randomUUID())
  useEffect(() => { obtenerLaboratorios().then(setLaboratorios).catch(() => setLaboratorios([])) }, [])
  const cambiar = (name: string, value: string | number) => { setForm((actual) => ({ ...actual, [name]: value })); key.current = crypto.randomUUID(); setDisponibilidad(null); setExito(null) }
  const comprobar = async () => { setConsultando(true); setError(null); try { setDisponibilidad(await consultarDisponibilidad(form.laboratorioId, form.fechaReserva, form.horaInicio, form.horaFin)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo consultar disponibilidad.') } finally { setConsultando(false) } }
  const enviar = async (event: FormEvent) => { event.preventDefault(); if (enviando) return; setEnviando(true); setError(null); try { const datos: CrearSolicitudReserva = { ...form, solicitanteId: usuario?.perfilId ?? '' }; const solicitud = await crearSolicitud(datos, key.current); setExito(`Solicitud ${solicitud.id} creada correctamente.`) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo crear la solicitud.') } finally { setEnviando(false) } }
  return <DashboardLayout breadcrumb="Reservas / Nueva solicitud"><section className="reservas-panel"><h1>Nueva solicitud</h1><form className="reserva-form" onSubmit={enviar}>
    <label>Laboratorio<select required value={form.laboratorioId} onChange={(e) => cambiar('laboratorioId', e.target.value)}><option value="">Seleccione</option>{laboratorios.map((lab) => <option key={lab.id} value={lab.id}>{lab.codigo} — {lab.nombre}</option>)}</select></label>
    <label>Docente ID<input required value={form.docenteId} onChange={(e) => cambiar('docenteId', e.target.value)} /></label><label>Materia ID<input required value={form.materiaId} onChange={(e) => cambiar('materiaId', e.target.value)} /></label><label>Periodo lectivo ID<input required value={form.periodoLectivoId} onChange={(e) => cambiar('periodoLectivoId', e.target.value)} /></label>
    <label>Fecha<input required type="date" min={new Date().toISOString().slice(0, 10)} value={form.fechaReserva} onChange={(e) => cambiar('fechaReserva', e.target.value)} /></label><label>Hora inicio<input required type="time" value={form.horaInicio} onChange={(e) => cambiar('horaInicio', e.target.value)} /></label><label>Hora fin<input required type="time" value={form.horaFin} onChange={(e) => cambiar('horaFin', e.target.value)} /></label><label>Participantes<input required min="1" type="number" value={form.numeroParticipantes} onChange={(e) => cambiar('numeroParticipantes', Number(e.target.value))} /></label>
    <label className="reserva-form__wide">Motivo<textarea required maxLength={500} value={form.motivo} onChange={(e) => cambiar('motivo', e.target.value)} /></label><label className="reserva-form__wide">Observación<textarea maxLength={2000} value={form.observacion} onChange={(e) => cambiar('observacion', e.target.value)} /></label>
    <div className="reserva-form__actions"><button type="button" disabled={consultando || !form.laboratorioId || !form.fechaReserva || !form.horaInicio || !form.horaFin || form.horaFin <= form.horaInicio} onClick={() => void comprobar()}>{consultando ? 'Consultando...' : 'Comprobar disponibilidad'}</button><button type="submit" disabled={enviando}>{enviando ? 'Enviando...' : 'Crear solicitud'}</button></div>
    {disponibilidad && <p role="status" className={disponibilidad.disponible ? 'availability--ok' : 'availability--conflict'}>{disponibilidad.disponible ? 'Horario disponible.' : `Horario no disponible${disponibilidad.motivo ? `: ${disponibilidad.motivo}` : '.'}`}</p>}{error && <p role="alert">{error}</p>}{exito && <p role="status">{exito}</p>}
  </form></section></DashboardLayout>
}
