import { render, screen } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { AuthUser } from '../../types/auth'
import * as api from './reservasApi'
import * as academico from '../../services/academicoApi'
import { SolicitudDetailPage } from './SolicitudDetailPage'

let usuario: AuthUser
vi.mock('../../auth', async (original) => ({ ...(await original<typeof import('../../auth')>()), useAuth: () => ({ usuario }) }))
vi.mock('./reservasApi', async (original) => ({ ...(await original<typeof import('./reservasApi')>()), obtenerSolicitudPorId: vi.fn(), obtenerHistorialSolicitud: vi.fn(), ponerEnRevision: vi.fn(), aprobarSolicitud: vi.fn(), rechazarSolicitud: vi.fn(), cancelarSolicitud: vi.fn(), proponerAlternativa: vi.fn(), responderPropuesta: vi.fn() }))
vi.mock('../../services/academicoApi')
vi.mock('../../components/DashboardLayout', () => ({ DashboardLayout: ({ children }: { children: React.ReactNode }) => <>{children}</> }))
const baseUser = { id: 'u', perfilId: 'perfil-1', username: 'demo', nombres: '', apellidos: '', emailInstitucional: '', tiposPerfil: [] }
const baseSolicitud = { id: 's1', solicitanteId: 'perfil-1', docenteId: 'd1', laboratorioId: 'lab-1', materiaId: 'm1', periodoLectivoId: 'pe1', fechaReserva: '2026-08-20', horaInicio: '08:00', horaFin: '10:00', numeroParticipantes: 20, motivo: 'Clase', observacion: '', estado: 'PENDIENTE' as api.EstadoSolicitud, propuestaFecha: null, propuestaHoraInicio: null, propuestaHoraFin: null, propuestaLaboratorioId: null, propuestaObservacion: null, reservaId: null, creadaEn: '', actualizadaEn: '', version: 0 }
function page() { render(<MemoryRouter initialEntries={['/solicitudes/s1']}><Routes><Route path="/solicitudes/:id" element={<SolicitudDetailPage />} /></Routes></MemoryRouter>) }
describe('SolicitudDetailPage', () => {
  beforeEach(() => { vi.resetAllMocks(); vi.mocked(api.obtenerHistorialSolicitud).mockResolvedValue([]); vi.mocked(academico.obtenerLaboratorios).mockResolvedValue([{ id: 'lab-1', pisoId: 'p1', codigo: 'LAB-A', nombre: 'Redes', capacidad: 20, descripcion: '', estado: 'DISPONIBLE', activo: true, creadoEn: '', actualizadoEn: '' }]); vi.mocked(academico.obtenerMaterias).mockResolvedValue([{ id: 'm1', carreraId: 'c1', codigo: 'MAT-A', nombre: 'Redes', numeroHoras: 40, activo: true }]) })
  it('DOCENTE propietario acepta/rechaza propuesta y no ve formulario gestor', async () => { usuario = { ...baseUser, roles: ['DOCENTE'], permisos: ['SOLICITUD_CREAR', 'SOLICITUD_CANCELAR'] }; vi.mocked(api.obtenerSolicitudPorId).mockResolvedValue({ ...baseSolicitud, estado: 'PROPUESTA', propuestaFecha: '2026-08-21', propuestaHoraInicio: '09:00', propuestaHoraFin: '11:00', propuestaLaboratorioId: 'lab-1', propuestaObservacion: 'Alternativa' }); page(); expect(await screen.findByRole('button', { name: 'Aceptar propuesta' })).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Rechazar propuesta' })).toBeInTheDocument(); expect(screen.queryByRole('heading', { name: 'Proponer alternativa' })).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Cancelar/Retirar' })).toBeInTheDocument() })
  it('ADMINISTRADOR_PISO puede aprobar, rechazar y proponer en revisión', async () => { usuario = { ...baseUser, perfilId: 'gestor', roles: ['ADMINISTRADOR_PISO'], permisos: ['SOLICITUD_APROBAR', 'SOLICITUD_RECHAZAR'] }; vi.mocked(api.obtenerSolicitudPorId).mockResolvedValue({ ...baseSolicitud, estado: 'EN_REVISION' }); page(); expect(await screen.findByRole('button', { name: 'Aprobar' })).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Rechazar' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Proponer alternativa' })).toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Aceptar propuesta' })).not.toBeInTheDocument() })
  it('usuario sin permiso no ve acciones operativas', async () => { usuario = { ...baseUser, perfilId: 'otro', roles: ['DECANO'], permisos: ['RESERVA_LEER'] }; vi.mocked(api.obtenerSolicitudPorId).mockResolvedValue({ ...baseSolicitud, estado: 'EN_REVISION' }); page(); await screen.findByText('EN REVISION'); expect(screen.queryByRole('button', { name: 'Aprobar' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Rechazar' })).not.toBeInTheDocument(); expect(screen.queryByRole('heading', { name: 'Proponer alternativa' })).not.toBeInTheDocument() })
  it('no ofrece cancelar o retirar en un estado terminal', async () => { usuario = { ...baseUser, roles: ['DOCENTE'], permisos: ['SOLICITUD_CANCELAR'] }; vi.mocked(api.obtenerSolicitudPorId).mockResolvedValue({ ...baseSolicitud, estado: 'RECHAZADA' }); page(); await screen.findByText('RECHAZADA'); expect(screen.queryByRole('button', { name: 'Cancelar/Retirar' })).not.toBeInTheDocument() })
})
