import { useCallback,useEffect,useMemo,useState } from 'react'
import { DashboardLayout } from '../../components/DashboardLayout'
import { obtenerLaboratorios,obtenerMaterias,obtenerPeriodos,type Laboratorio,type Materia,type PeriodoLectivo } from '../../services/academicoApi'
import { listarParticipantesUsoPiso,listarUsosPiso,type ParticipanteUso,type SesionAsistencia } from '../../services/operationalApi'
import '../operaciones/Operations.css'

export function AdminUsoLaboratoriosPage(){const [usos,setUsos]=useState<SesionAsistencia[]>([]);const [labs,setLabs]=useState<Laboratorio[]>([]);const [materias,setMaterias]=useState<Materia[]>([]);const [periodos,setPeriodos]=useState<PeriodoLectivo[]>([]);const [detalle,setDetalle]=useState<SesionAsistencia|null>(null);const [participantes,setParticipantes]=useState<ParticipanteUso[]>([]);const [filtros,setFiltros]=useState({fecha:'',periodoId:'',laboratorioId:'',materiaId:'',estado:''});const [error,setError]=useState('')
  const cargar=useCallback(()=>Promise.all([listarUsosPiso(filtros),obtenerLaboratorios(),obtenerMaterias(),obtenerPeriodos()]).then(([u,l,m,p])=>{setUsos(u);setLabs(l);setMaterias(m);setPeriodos(p)}).catch(e=>setError(e instanceof Error?e.message:'No fue posible cargar los registros')),[filtros])
  useEffect(()=>{void cargar()},[cargar])
  const lab=useMemo(()=>new Map(labs.map(x=>[x.id,x])),[labs]);const mat=useMemo(()=>new Map(materias.map(x=>[x.id,x])),[materias])
  async function abrir(item:SesionAsistencia){setDetalle(item);setParticipantes(await listarParticipantesUsoPiso(item.id))}
  return <DashboardLayout breadcrumb="Uso de laboratorios"><section className="operations"><header className="operations__header"><div><span className="operations__eyebrow">Administración operativa del piso</span><h1>Registro de uso de laboratorios</h1><p>Consulta técnica de los usos realizados en los laboratorios de su piso.</p></div></header>{error&&<p role="alert" className="operations__error">{error}</p>}
    <div className="operations__filters"><label>Fecha<input type="date" value={filtros.fecha} onChange={e=>setFiltros({...filtros,fecha:e.target.value})}/></label><label>Período<select value={filtros.periodoId} onChange={e=>setFiltros({...filtros,periodoId:e.target.value})}><option value="">Todos</option>{periodos.map(x=><option key={x.id} value={x.id}>{x.codigo}</option>)}</select></label><label>Laboratorio<select value={filtros.laboratorioId} onChange={e=>setFiltros({...filtros,laboratorioId:e.target.value})}><option value="">Todos</option>{labs.map(x=><option key={x.id} value={x.id}>{x.codigo}</option>)}</select></label><label>Materia<select value={filtros.materiaId} onChange={e=>setFiltros({...filtros,materiaId:e.target.value})}><option value="">Todas</option>{materias.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><label>Estado<select value={filtros.estado} onChange={e=>setFiltros({...filtros,estado:e.target.value})}><option value="">Todos</option><option>ABIERTA</option><option>CERRADA</option><option>VENCIDA</option></select></label><button onClick={()=>void cargar()}>Aplicar filtros</button></div>
    <div className="operations__table-wrap"><table><thead><tr><th>Fecha</th><th>Horario</th><th>Laboratorio</th><th>Materia</th><th>Carrera/Nivel</th><th>Estado de uso</th><th>Esperados</th><th>Presentes</th><th>No registrados/Ausentes</th></tr></thead><tbody>{usos.map(x=><tr key={x.id} onClick={()=>void abrir(x)} tabIndex={0}><td>{x.fechaClase}</td><td>{x.horaInicio}–{x.horaFin}</td><td>{lab.get(x.laboratorioId??'')?.codigo??'Laboratorio'}</td><td>{mat.get(x.materiaId??'')?.nombre??'Materia'}</td><td>{x.carreraId?.slice(0,8)} · {x.nivel}°</td><td>{x.estado}</td><td>{x.esperados??0}</td><td>{x.presentes??0}</td><td>{(x.esperados??0)-(x.presentes??0)}</td></tr>)}</tbody></table>{usos.length===0&&<p className="operations__empty">No existen registros de uso para los filtros seleccionados.</p>}</div>
    {detalle&&<article className="operations__card"><h2>Detalle del registro de uso</h2><p><strong>Tema/actividad:</strong> {detalle.temaActividad??'Pendiente de registrar'}</p><p><strong>Observación:</strong> {detalle.observacionUso??'Sin observaciones'}</p><p><strong>Apertura:</strong> {new Date(detalle.abiertaEn).toLocaleString()}</p><p><strong>Cierre:</strong> {detalle.cerradaEn?new Date(detalle.cerradaEn).toLocaleString():'En curso'}</p><h3>Estudiantes relacionados</h3>{participantes.map(p=><p key={p.id}>{p.estudiantePerfilId} · <strong>{p.estado}</strong>{p.registradaEn?` · ${new Date(p.registradaEn).toLocaleTimeString()}`:''}</p>)}</article>}
  </section></DashboardLayout>}
